#!/usr/bin/env python3
r"""v1.06 protocol tests: PGLZ byte-compatibility end-to-end.

Grounded in PostgreSQL REL_19_STABLE:
- src/common/pg_lzcompress.c (pglz_compress/pglz_decompress, default
  strategy): the compressor's payload bytes are proven byte-identical to
  PG19's by the Rust differential tests (toast::tests::v106_*, thousands
  of inputs incl. 1MB, plus ~90k mutated-payload decompressor cases).
  What this suite proves is that those exact bytes flow through the
  engine: INSERT/SELECT round-trips, pg_column_compression(), UPDATE
  (v1.05 toast reuse path), restart/WAL replay, and the lz4 column
  method are all behavior-preserving.
- src/backend/access/common/toast_compression.c: pg_column_compression
  reports the conventional 'pglz' name.

Self-starting: launches rustgres on 5451 with a fresh datadir, plus one
restart mid-suite to exercise WAL replay of toasted values.
"""
import socket, struct, subprocess, sys, time, os, shutil, hashlib

PORT = 5451
BIN = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "target", "debug", "rustgres")
DATADIR = "/tmp/rg_proto_v106_pglz"

# Deterministic 8000-char compressible text (seed 7, pat_frac 0.5): PG19's
# pglz_compress() turns it into a 4503-byte payload (framed 4507), which
# exceeds the 2037 toast target, so it is stored compressed-external.
# Regenerated by tests' companion script; the literal below is the exact
# input the C reference compressed.
WIDE_VAL = None  # filled by _wide_val()
WIDE_MD5 = "c11df1095d20f8dd48df55672d7353a8"


def _wide_val():
    import random
    rng = random.Random(7)
    n = 8000
    npat = int(n * 0.5)
    pat = ("word-" * 2000)[:npat]
    rnd = "".join(chr(rng.randrange(97, 123)) for _ in range(n - npat))
    return (pat + rnd)[:n]


def _incompressible(n, seed=12345):
    x = seed
    out = []
    for _ in range(n):
        x = (x * 6364136223846793005 + 1) & 0xFFFFFFFFFFFFFFFF
        out.append(chr(97 + ((x >> 33) % 26)))
    return "".join(out)


def msg(t, payload):
    return t + struct.pack("!I", 4 + len(payload)) + payload


def cstr(s):
    return s.encode() + b"\x00"


def read_exact(s, n):
    d = b""
    while len(d) < n:
        c = s.recv(n - len(d))
        if not c:
            raise RuntimeError("closed")
        d += c
    return d


def read_msg(s):
    t = read_exact(s, 1)
    ln = struct.unpack("!I", read_exact(s, 4))[0]
    return t, read_exact(s, ln - 4)


def msg_fields(payload):
    i = 0
    fields = {}
    while i < len(payload) - 1:
        f = payload[i:i+1]
        e = payload.index(b"\x00", i + 1)
        fields[f] = payload[i+1:e].decode()
        i = e + 1
    return fields


class Conn:
    def __init__(self, port=PORT):
        self.s = socket.create_connection(("127.0.0.1", port), timeout=30)
        params = b"user\x00postgres\x00database\x00postgres\x00\x00"
        self.s.sendall(struct.pack("!I", 8 + len(params)) + b"\x00\x03\x00\x00" + params)
        while True:
            t, p = read_msg(self.s)
            if t == b"Z":
                break

    def q(self, sql):
        """Returns (sets, notices, ready_status)."""
        self.s.sendall(msg(b"Q", cstr(sql)))
        sets = []
        cur = {"rows": [], "tag": None, "err": None}
        notices = []
        status = None
        while True:
            t, p = read_msg(self.s)
            if t == b"D":
                (n,) = struct.unpack("!h", p[:2])
                pos, r = 2, []
                for _ in range(n):
                    (ln,) = struct.unpack("!i", p[pos:pos+4])
                    pos += 4
                    if ln == -1:
                        r.append(None)
                    else:
                        r.append(p[pos:pos+ln].decode())
                        pos += ln
                cur["rows"].append(r)
            elif t == b"C":
                cur["tag"] = p[:-1].decode()
                sets.append(cur)
                cur = {"rows": [], "tag": None, "err": None}
            elif t == b"E":
                cur["err"] = msg_fields(p).get(b"C")
            elif t == b"N":
                notices.append(msg_fields(p).get(b"M", ""))
            elif t == b"Z":
                if cur["rows"] or cur["tag"] or cur["err"]:
                    sets.append(cur)
                status = p[:1].decode()
                break
        return sets, notices, status

    def close(self):
        self.s.close()


PASS = 0
FAIL = 0


def check(name, cond, detail=""):
    global PASS, FAIL
    if cond:
        PASS += 1
        print(f"PASS {name}")
    else:
        FAIL += 1
        print(f"FAIL {name} {detail}")


def start_server():
    proc = subprocess.Popen(
        [BIN, "--port", str(PORT), "--data-dir", DATADIR],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    time.sleep(2)
    return proc


def stop_server(proc):
    proc.terminate()
    try:
        proc.wait(timeout=15)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait()
    time.sleep(1)


def main():
    global WIDE_VAL
    WIDE_VAL = _wide_val()
    assert hashlib.md5(WIDE_VAL.encode()).hexdigest() == WIDE_MD5, "wide fixture drift"
    assert len(WIDE_VAL) == 8000
    shutil.rmtree(DATADIR, ignore_errors=True)
    proc = start_server()
    try:
        c = Conn()

        # --- wide compressible value: byte-exact round-trip ---
        sets, _, _ = c.q("CREATE TABLE t106pglz(v text)")
        check("create", sets[0]["tag"] == "CREATE TABLE", f"{sets[0]}")
        sets, _, _ = c.q("INSERT INTO t106pglz VALUES ('" + WIDE_VAL + "')")
        check("insert wide", sets[0]["tag"] == "INSERT 0 1", f"{sets[0]}")
        sets, _, _ = c.q("SELECT v FROM t106pglz")
        check("wide round-trip byte-exact",
              len(sets) == 1 and sets[0]["rows"] == [[WIDE_VAL]],
              f"rows={len(sets[0]['rows']) if sets else 0}")
        sets, _, _ = c.q("SELECT length(v) FROM t106pglz")
        check("wide length 8000", sets[0]["rows"] == [["8000"]], f"{sets[0]['rows']}")
        sets, _, _ = c.q("SELECT pg_column_compression(v) FROM t106pglz")
        check("pg_column_compression = pglz", sets[0]["rows"] == [["pglz"]],
              f"{sets[0]['rows']}")

        # --- small vector values through the engine path ---
        sets, _, _ = c.q("INSERT INTO t106pglz VALUES ('" + "A" * 32 + "')")
        check("insert 32xA", sets[0]["tag"] == "INSERT 0 1")
        sets, _, _ = c.q("SELECT v FROM t106pglz WHERE length(v) = 32")
        check("32xA round-trip", sets[0]["rows"] == [["A" * 32]], f"{sets[0]['rows']}")
        sets, _, _ = c.q("SELECT pg_column_compression('abc')")
        small_comp = sets[0]["rows"][0][0]
        check("small value not compressed", small_comp is None, f"{small_comp!r}")

        # --- UPDATE a wide value (v1.05 toast reuse path) ---
        new_wide = _wide_val()[::-1]  # reversed: still compressible, different bytes
        sets, _, _ = c.q("UPDATE t106pglz SET v = '" + new_wide + "' WHERE length(v) = 8000")
        check("update wide", sets[0]["tag"] == "UPDATE 1", f"{sets[0]}")
        sets, _, _ = c.q("SELECT v, length(v), pg_column_compression(v) FROM t106pglz WHERE length(v) = 8000")
        check("updated wide round-trip",
              sets[0]["rows"] == [[new_wide, "8000", "pglz"]],
              f"{[r[:2] for r in sets[0]['rows']]}")

        # --- incompressible wide value: external, uncompressed, exact ---
        inc = _incompressible(3000)
        sets, _, _ = c.q("CREATE TABLE t106inc(v text)")
        c.q("INSERT INTO t106inc VALUES ('" + inc + "')")
        sets, _, _ = c.q("SELECT v, length(v) FROM t106inc")
        check("incompressible round-trip", sets[0]["rows"] == [[inc, "3000"]],
              f"len={[len(r[0]) for r in sets[0]['rows']]}")
        sets, _, _ = c.q("SELECT pg_column_compression(v) FROM t106inc")
        check("incompressible not marked pglz", sets[0]["rows"][0][0] != "pglz",
              f"{sets[0]['rows']}")

        # --- bytea wide value ---
        sets, _, _ = c.q("CREATE TABLE t106b(v bytea)")
        hexval = "abcd" * 4000  # 16000 hex chars = 8000 bytes
        c.q("INSERT INTO t106b VALUES (decode('" + hexval + "', 'hex'))")
        sets, _, _ = c.q("SELECT encode(v, 'hex'), length(v) FROM t106b")
        check("bytea round-trip", sets[0]["rows"] == [[hexval, "8000"]],
              f"{sets[0]['rows'][0][1] if sets[0]['rows'] else None}")

        # --- lz4 column method still works ---
        sets, _, _ = c.q("CREATE TABLE t106lz(v text COMPRESSION lz4)")
        check("lz4 column create", sets[0]["err"] is None, f"{sets[0]}")
        c.q("INSERT INTO t106lz VALUES ('" + WIDE_VAL + "')")
        sets, _, _ = c.q("SELECT v, pg_column_compression(v) FROM t106lz")
        check("lz4 round-trip + label",
              sets[0]["rows"] == [[WIDE_VAL, "lz4"]],
              f"{[(len(r[0]), r[1]) for r in sets[0]['rows']]}")

        # --- restart: toasted values survive WAL replay ---
        c.close()
        stop_server(proc)
        proc = start_server()
        c = Conn()
        sets, _, _ = c.q("SELECT v FROM t106pglz WHERE length(v) = 8000")
        check("restart: updated wide survives",
              sets[0]["rows"] == [[new_wide]], f"{len(sets[0]['rows'])} rows")
        sets, _, _ = c.q("SELECT v FROM t106inc")
        check("restart: incompressible survives", sets[0]["rows"] == [[inc]],
              f"{len(sets[0]['rows'])} rows")
        sets, _, _ = c.q("SELECT v FROM t106lz")
        check("restart: lz4 survives", sets[0]["rows"] == [[WIDE_VAL]],
              f"{len(sets[0]['rows'])} rows")
        sets, _, _ = c.q("SELECT pg_column_compression(v) FROM t106pglz WHERE length(v) = 8000")
        check("restart: still pglz", sets[0]["rows"] == [["pglz"]], f"{sets[0]['rows']}")
        c.close()
    finally:
        stop_server(proc)

    print(f"\n{v106_summary()}")
    sys.exit(1 if FAIL else 0)


def v106_summary():
    return f"v106 pglz: {PASS} passed, {FAIL} failed"


if __name__ == "__main__":
    main()
