#!/usr/bin/env python3
"""protocol_test40.py — v0.40 PG19 PGLZ byte compatibility.

v0.40 replaces rustgres's custom LZ77 with a faithful port of PG19's
`pglz_compress()` (REL_19_STABLE `src/common/pg_lzcompress.c`, default
strategy): for a given input the payload bytes are identical to
PostgreSQL 19's, and compression is refused under exactly PG's
conditions (input < 32 bytes, payload must beat 75% of the input, give
up if no match is found by 1024 output bytes). The old code needed a
64-byte minimum and a custom byte format.

Also bundled: decimal literals now follow PG19's `scan.l` — an
identifier char right after a decimal literal is "trailing junk after
numeric literal" (42601), and single underscores may separate digits
(`1_000` = 1000).

This test manages its own server on port 5544 (so it never collides
with the conformance runner) and is RED on the v0.39 base, GREEN on
the v0.40 branch.

Sections:
  A. PG19 compression decisions via pg_column_compression: a 40-byte
     compressible value (below the old 64-byte minimum) is now
     compressed inline ('pglz'); on the base it is not.
  B. The exact PG19 payload bytes are visible in the toast table's
     chunk_data: byte-identity with PostgreSQL 19 at the SQL level.
     (Expected bytes generated by compiling PG19's real
     `pglz_compress()` and running it over the test input.)
  C. Decimal trailing junk: `123abc` / `1.2foo` / `1e2bar` -> 42601;
     `1_000` -> 1000; ordinary decimals/exponents still parse.
"""
import os
import socket
import struct
import subprocess
import sys
import tempfile
import time

PORT = 5544
BIN = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "target", "debug", "rustgres")

passed = failed = 0


def check(name, cond):
    global passed, failed
    if cond:
        passed += 1
    else:
        failed += 1
        print(f"FAIL {name}")


# --------------------------------------------------------------------------
# Server lifecycle.
# --------------------------------------------------------------------------

def start_server(data_dir):
    proc = subprocess.Popen(
        [BIN, "--data-dir", data_dir, "--port", str(PORT)],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for _ in range(100):
        try:
            s = socket.create_connection(("127.0.0.1", PORT), timeout=1)
            s.close()
            return proc
        except OSError:
            time.sleep(0.1)
    proc.kill()
    raise RuntimeError("server did not start")


def stop_server(proc):
    try:
        proc.terminate()
        proc.wait(timeout=10)
    except Exception:
        proc.kill()
    time.sleep(0.5)


# --------------------------------------------------------------------------
# Wire protocol.
# --------------------------------------------------------------------------

class Conn:
    def __init__(self):
        self.s = socket.create_connection(("127.0.0.1", PORT), timeout=10)
        body = struct.pack("!i", 196608) + b"user\x00postgres\x00\x00"
        self.s.sendall(struct.pack("!i", len(body) + 4) + body)
        while True:
            t, _ = self.read_msg()
            if t == b"Z":
                break

    def read_exact(self, n):
        d = b""
        while len(d) < n:
            c = self.s.recv(n - len(d))
            if not c:
                raise RuntimeError("closed")
            d += c
        return d

    def read_msg(self):
        t = self.read_exact(1)
        (ln,) = struct.unpack("!i", self.read_exact(4))
        return t, self.read_exact(ln - 4)

    def do_sql(self, q):
        self.s.sendall(b"Q" + struct.pack("!i", len(q.encode()) + 5)
                       + q.encode() + b"\x00")
        rows, err, msg = [], None, None
        while True:
            t, p = self.read_msg()
            if t == b"D":
                (n,) = struct.unpack("!h", p[:2])
                pos, row = 2, []
                for _ in range(n):
                    (ln,) = struct.unpack("!i", p[pos:pos + 4])
                    pos += 4
                    if ln == -1:
                        row.append(None)
                    else:
                        row.append(p[pos:pos + ln].decode())
                        pos += ln
                rows.append(row)
            elif t == b"E":
                f, pos = {}, 0
                while pos < len(p) and p[pos] != 0:
                    c = chr(p[pos])
                    pos += 1
                    e = p.index(b"\x00", pos)
                    f[c] = p[pos:e].decode("utf8", "replace")
                    pos = e + 1
                err, msg = f.get("C"), f.get("M")
            elif t == b"Z":
                break
        return rows, err, msg

    def val(self, q):
        rows, err, msg = self.do_sql(q)
        assert not err, f"{q} -> SQLSTATE {err}: {msg}"
        assert len(rows) == 1 and len(rows[0]) == 1, f"{q} -> {rows}"
        return rows[0][0]

    def close(self):
        self.s.close()


def toast_table(c, table):
    return c.val(
        f"SELECT reltoastrelid::regclass FROM pg_class WHERE relname='{table}'")


# PG19's exact compressed bytes for
# repeat('The quick brown fox jumps over the lazy dog. ', 110)
# (4950 bytes): 4-byte LE original length + 107-byte PGLZ payload, taken
# from the real REL_19_STABLE pglz_compress() with the default strategy.
# The framed 111 bytes exceed the 104-byte toast target below, so the
# value goes out-of-line compressed in a single chunk.
EXPECTED_CHUNK_HEX = (
    "56130000"
    "005468652071756963006b2062726f776e2000666f78206a756d700073206f76657220"
    "74006865206c617a7920e0646f672e200f2dff0f2dff0f2dffff0f2dff0f2dff0f2dff0f"
    "2dff0f2dff0f2dff0f2dff0f2dff7f0f2dff0f2dff0f2dff0f2dff0f2dff0f2dff0f2df6"
)


def main():
    data_dir = tempfile.mkdtemp(prefix="rg40_")
    proc = start_server(data_dir)
    try:
        c = Conn()

        # A. PG19 compression decisions.
        c.do_sql("DROP TABLE IF EXISTS t40pglz")
        c.do_sql("CREATE TABLE t40pglz(a text, b text, c text)")
        c.do_sql("ALTER TABLE t40pglz SET (toast_tuple_target = 128)")
        c.do_sql("INSERT INTO t40pglz VALUES "
                 "(repeat('A', 60), repeat('B', 2000), repeat('C', 2000))")
        # The 60-byte value is below the old 64-byte minimum: the base
        # leaves it uncompressed (NULL), the branch reports 'pglz'.
        check("A1 60-byte value compressed (PG 32-byte minimum)",
              c.val("SELECT pg_column_compression(a) FROM t40pglz") == "pglz")
        check("A2 big value b compressed",
              c.val("SELECT pg_column_compression(b) FROM t40pglz") == "pglz")
        check("A3 big value c compressed",
              c.val("SELECT pg_column_compression(c) FROM t40pglz") == "pglz")
        check("A4 roundtrip",
              c.val("SELECT length(a) || '/' || length(b) || '/' || length(c)"
                    " FROM t40pglz") == "60/2000/2000")

        # B. Exact PG19 payload bytes in the toast table.
        c.do_sql("DROP TABLE IF EXISTS t40bytes")
        c.do_sql("CREATE TABLE t40bytes(a text)")
        c.do_sql("ALTER TABLE t40bytes SET (toast_tuple_target = 128)")
        c.do_sql("INSERT INTO t40bytes VALUES "
                 "(repeat('The quick brown fox jumps over the lazy dog. ', 110))")
        tt = toast_table(c, "t40bytes")
        check("B1 one chunk",
              c.val(f"SELECT count(*) FROM {tt}") == "1")
        check("B2 chunk bytes are PG19's exact PGLZ stream",
              c.val(f"SELECT encode(chunk_data, 'hex') FROM {tt}"
                    f" WHERE chunk_seq = 0") == EXPECTED_CHUNK_HEX)
        check("B3 pg_column_compression",
              c.val("SELECT pg_column_compression(a) FROM t40bytes") == "pglz")
        check("B4 roundtrip",
              c.val("SELECT length(a) FROM t40bytes") == "4950")

        # C. Decimal trailing junk (PG19 scan.l).
        for q in ("SELECT 123abc", "SELECT 1.2foo", "SELECT 1e2bar"):
            _, err, _ = c.do_sql(q)
            check(f"C1 {q} -> 42601", err == "42601")
        _, err, msg = c.do_sql("SELECT 123abc")
        check("C2 message text",
              msg == "syntax error: trailing junk after numeric literal")
        check("C3 1_000 = 1000", c.val("SELECT 1_000") == "1000")
        check("C4 1_000_000 = 1000000",
              c.val("SELECT 1_000_000") == "1000000")
        check("C5 plain decimal still parses",
              c.val("SELECT 1.5") == "1.5")
        check("C6 exponent still parses",
              c.val("SELECT 1e3") == "1000")
        check("C7 negative exponent still parses",
              c.val("SELECT 1.5e-3") == "0.0015")

        c.do_sql("DROP TABLE t40pglz")
        c.do_sql("DROP TABLE t40bytes")
        c.close()
    finally:
        stop_server(proc)

    print(f"protocol_test40: {passed} passed, {failed} failed")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
